### ISSUE TITLE
Edit Entity button not showing

### ISSUE THREAD

**Issue by bastianlb** [SysCV/nutsh#12]
Hi, thanks for the cool project. It seems like there is already a lot of useful functionality. 

I just installed it (version 43168af9 43168af9 2023-11-20T14:25:47+08:00); somehow I can't edit properties on entities, which makes it tricky to manage my annotations. It seems like a button to edit the entities is missing which is present on webpage demos. Could you advise? I tried this on both Firefox and Chrome.

<img width="300" alt="image" src="https://github.com/SysCV/nutsh/assets/8620425/4f72cce0-01e2-4c53-b476-1111c528eeb7">

**Comment by hxhxhx88** [comment]
Hello @bastianlb!

It seems that the `categories` field of your [project specification](https://nutsh.ai/docs/Usage/Project#specification) is missing. Could you share your project specification with me?

You can retrieve your project specification by visiting the following url in your browser:
```
${YOUR_NUTSH_ORIGIN}/api/project/${PROJECT_ID}
```
or you can click the info icon at the top right corner of the project page and give me a screenshot.
![image](https://github.com/SysCV/nutsh/assets/1113875/2f2f49b6-c96f-4dea-b71a-02d71e88af05)

**Comment by bastianlb** [comment]
Thanks for the quick response! I guess this was a user error when setting up the project, I'll go ahead and close the issue.

Is it possible to change the project specifications (e.g. label attributes) through the UI? As far as I can see from the docs, the best way to do this might be exporting, modifying the json schema, and re-importing the project.

**Comment by hxhxhx88** [comment]
@bastianlb indeed for now it is impossible to change the project specification through UI, which is a one-time deal upon creation. I'll put it into todo list. Thanks for the input!
