### ISSUE TITLE
Documentation not accessible

### ISSUE THREAD

**Issue by luisatheelke** [SysCV/nutsh#14]
Hi, 
I am using Nutsh to label medical images. Unfortunately, the documentation has not been available for a few weeks now. It was very helpful, especially for medical professionals, to be able to look up the various functions and watch the explanatory videos there. Are there plans to put the documentation back online?

**Comment by hxhxhx88** [comment]
Hi. Presumably you have run nutsh locally. In that case, simply visit `http://localhost:12346/docs` will navigate you to the docs. (Change `http://localhost:12346` to the url you use to visit nutsh locally.)
