### ISSUE TITLE
Data from local disk

### ISSUE THREAD

**Issue by mjan2021** [SysCV/nutsh#2]
This more of a question than issue but I am trying to load the data from a local folder,  the document haven't mentioned anything regarding frames/video to be imported from a local folder. Does it need to be in a specific place, or full local directory path work also?

Looking forward to starting the annotation process for a large-scale dataset. 

Thanks 

OS: MacOS 14 Sonoma
System: Macbook Pro M2 Max

**Comment by hxhxhx88** [comment]
Hi @mjan2021 , for the moment only urls are supported, and we are working on loading local files. It will come soon and I'll let you know:) Before that, a quick work around will be to server the local folder behind a proxy like the nginx.

**Comment by mjan2021** [comment]
@hxhxhx88 It also not loading from the NGINX, I also tried to deploy Flask server but it also not loading. 
![image](https://github.com/SysCV/nutsh/assets/77818526/417d33d4-0a12-4584-9ea4-a3192c1a5459)

**Comment by hxhxhx88** [comment]
@mjan2021 hi, serving local files is added to v0.1.2. Please check [the release](https://github.com/SysCV/nutsh/releases/tag/v0.1.2) and [the doc](https://nutsh.ai/docs/Usage/Resource#loading-local-files)!

**Comment by mjan2021** [comment]
@hxhxhx88. Perfect! Works like a charm. Looking forward to further development of this app. 

Also, just to let you know, the Flask 2.3.3 was giving an error with python 3.10.11 when starting SAM. I had to remove the static version to make it work.
