### ISSUE TITLE
Smart Segment do not work.

### ISSUE THREAD

**Issue by leonlee723** [SysCV/nutsh#3]
I have installed the nutsh+sam module on my Macbook pro M1 following the official documents. And nutsh can successful startup, then I can use it through the browser. 
But when I used smart segment, the nutsh show a error what is "something is worng"
<img width="1676" alt="image" src="https://github.com/SysCV/nutsh/assets/2637309/475ae8b2-03d3-4dc9-8f2f-63334f4630a8">

And I got another error on my teminal of sam module, as below
<img width="1370" alt="image" src="https://github.com/SysCV/nutsh/assets/2637309/f33c8d67-8cd4-455c-b19c-e8c4eb595953">

BTW, I modified starting command of sam-module. I used  "--devices mps" instead of  "--devices cuda:0"
How do I solve the problem? Thank your.

**Comment by leonlee723** [comment]
I have solved the issue.

**Comment by hxhxhx88** [comment]
@leonlee723 hi, I was told somewhere else also about this error. May you tell me what was the reason and how you solved it?
