### ISSUE TITLE
Unable to load image file

### ISSUE THREAD

**Issue by prnr** [SysCV/nutsh#8]
{"level":"info","ts":1698826922.2076354,"caller":"action/start.go:50","msg":"request","method":"GET","uri":"/data/sk_images/3_24.png","latency":0.000188728,"status":404}

I've never changed the job folder, nor have I added or deleted files. As soon as I finished working on the 37th image and moved on to the next page, the message [slice] appeared where the image was supposed to be printed, and all the images were unable to me.

**Comment by prnr** [comment]
Sorry, I forgot to specify --data-dir at first drive. Could you tell me where the default value is designated?

**Comment by hxhxhx88** [comment]
@prnr Sorry I am not quite sure what you are asking. If you are asking what is the default value of `--data-dir`, the answer is there is no default value for it, and by default no local files are served.
